# Generated by Django 5.0.4 on 2024-06-10 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0015_alter_bodyversion_arm_circumference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('cancelled', 'cancelled'), ('expired', 'expired'), ('paid-and-waiting-for-program', 'paid-and-waiting-for-program'), ('new-and-payment-pending', 'new-and-payment-pending'), ('completed', 'completed')], default='new-and-payment-pending', max_length=40)),
                ('type', models.CharField(choices=[('nutrition', 'nutrition'), ('workout', 'workout'), ('supplement', 'supplement'), ('full', 'full')], default='workout', max_length=40)),
                ('target', models.CharField(blank=True, max_length=1000, null=True)),
                ('experience', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.coachprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
