# Generated by Django 5.0.4 on 2024-06-12 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0015_alter_bodyversion_arm_circumference_and_more'),
        ('nutrition', '0006_alter_nutrition_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=4000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=4000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='payment')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workout_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saturday', models.JSONField(blank=True, max_length=10000, null=True)),
                ('sunday', models.JSONField(blank=True, max_length=10000, null=True)),
                ('monday', models.JSONField(blank=True, max_length=10000, null=True)),
                ('tuesday', models.JSONField(blank=True, max_length=10000, null=True)),
                ('wednesday', models.JSONField(blank=True, max_length=10000, null=True)),
                ('thursday', models.JSONField(blank=True, max_length=10000, null=True)),
                ('friday', models.JSONField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition_program_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('time', models.CharField(max_length=100)),
                ('nutrition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutrition.nutrition')),
                ('nutrition_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.nutrition_program')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('cancelled', 'cancelled'), ('expired', 'expired'), ('paid-and-waiting-for-program', 'paid-and-waiting-for-program'), ('new-and-payment-pending', 'new-and-payment-pending'), ('completed', 'completed')], default='new-and-payment-pending', max_length=40)),
                ('type', models.CharField(choices=[('nutrition', 'nutrition'), ('workout', 'workout'), ('supplement', 'supplement'), ('full', 'full')], default='workout', max_length=40)),
                ('target', models.CharField(blank=True, max_length=1000, null=True)),
                ('experience', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, max_length=4000, null=True)),
                ('duration_day', models.IntegerField(default=45)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.coachprofile')),
                ('nutrition_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.nutrition_program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program_payment')),
                ('workout_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.workout_program')),
            ],
        ),
    ]
