# Generated by Django 5.0.4 on 2024-06-12 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
        ('supplement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=4000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='supplement_program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='program.supplement_program'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Supplement_program_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('time', models.CharField(max_length=100)),
                ('supplement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplement.supplement')),
                ('supplement_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.supplement_program')),
            ],
        ),
    ]
