# Generated by Django 5.0.4 on 2024-06-11 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program_payment',
            name='program',
        ),
        migrations.AddField(
            model_name='program',
            name='payment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='program.program_payment'),
            preserve_default=False,
        ),
    ]
