# Generated by Django 5.0.4 on 2024-06-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
