# Generated by Django 5.0.4 on 2024-06-12 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_supplement_program_program_supplement_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='nutrition_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.nutrition_program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.program_payment'),
        ),
        migrations.AlterField(
            model_name='program',
            name='supplement_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.supplement_program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='workout_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='program.workout_program'),
        ),
    ]
