# Generated by Django 5.0.4 on 2024-06-10 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_alter_program_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=4000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='payment')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
            ],
        ),
    ]
