# Generated by Django 5.0.4 on 2024-06-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_program_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_payment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
