# Generated by Django 5.0.4 on 2024-06-12 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_bodyversion_arm_circumference_and_more'),
        ('program', '0003_alter_program_nutrition_program_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_payment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
            preserve_default=False,
        ),
    ]
