# Generated by Django 5.0.4 on 2024-05-04 13:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_content_remove_chat_time_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('user1', 'user2'), ('user2', 'user1')},
        ),
    ]
