# Generated by Django 5.0.4 on 2024-04-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_username_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('coach', 'coach'), ('normal', 'normal')], default='normal', max_length=8),
        ),
    ]
