# Generated by Django 5.0.4 on 2024-04-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_coachprofile_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachprofile',
            name='data',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='data',
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('coach', 'coach'), ('normal', 'normal'), ('unknown', 'unknown')], default='unknown', max_length=8),
        ),
    ]
