# Generated by Django 5.0.4 on 2024-04-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_coachprofile_data_remove_userprofile_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='cover',
            field=models.ImageField(default='coach_cover/default.png', upload_to='coach_cover'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=128),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='image',
            field=models.ImageField(default='coach_img/default.png', upload_to='coach_img'),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='instagram',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
