# Generated by Django 5.0.4 on 2024-05-06 07:32

import accounts.models.normal_profile
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_coachprofile_bio_certificate_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=128),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='user_img/default.png', upload_to='user_img'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='injury',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.CreateModel(
            name='BodyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='وزن')),
                ('arm_circumference', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='دور بازو')),
                ('forehand_circumference', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='دور ساعد')),
                ('chest_circumference', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='دور سینه')),
                ('stomach_circumference', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='دور شکم')),
                ('waist_circumference', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='دور کمر')),
                ('hip_circumference', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='دور باسن')),
                ('thigh_circumference', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='دور ران')),
                ('leg_circumference', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='دور ساق')),
                ('front_double_biceps', models.ImageField(default='body_version/default.png', upload_to=accounts.models.normal_profile.img_path)),
                ('back_double_biceps', models.ImageField(default='body_version/default.png', upload_to=accounts.models.normal_profile.img_path)),
                ('front_normal', models.ImageField(default='body_version/default.png', upload_to=accounts.models.normal_profile.img_path)),
                ('back_normal', models.ImageField(default='body_version/default.png', upload_to=accounts.models.normal_profile.img_path)),
                ('left_side', models.ImageField(default='body_version/default.png', upload_to=accounts.models.normal_profile.img_path)),
                ('right_side', models.ImageField(default='body_version/default.png', upload_to=accounts.models.normal_profile.img_path)),
                ('in_body_file', models.FileField(blank=True, null=True, upload_to=accounts.models.normal_profile.img_path)),
                ('medical_checkup_file', models.FileField(blank=True, null=True, upload_to=accounts.models.normal_profile.img_path)),
                ('description', models.CharField(blank=True, max_length=4000, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
