# Generated by Django 5.0.4 on 2024-05-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_gender_userprofile_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyversion',
            name='activity_type',
            field=models.CharField(choices=[('کم تحرک (کمی یا بدون ورزش)', 'کم تحرک (کمی یا بدون ورزش)'), ('کم تحرک (ورزش سبک 1 تا 3 ساعت در هفته)', 'کم تحرک (ورزش سبک 1 تا 3 ساعت در هفته)'), ('فعالیت متوسط (۳ الی ۵ ساعت در هفته)', 'فعالیت متوسط (۳ الی ۵ ساعت در هفته)'), ('بسیار فعال (۶ الی ۷ ساعت در هفته)', 'بسیار فعال (۶ الی ۷ ساعت در هفته)'), ('فعالیت بسیار بالا (فعالیت سخت ورزشی و کاری)', 'فعالیت بسیار بالا (فعالیت سخت ورزشی و کاری)')], default='فعالیت متوسط (۳ الی ۵ ساعت در هفته)', max_length=256),
        ),
    ]
