# Generated by Django 5.0.4 on 2024-05-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_bodyversion_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyversion',
            name='BMI',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bodyversion',
            name='BMR',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bodyversion',
            name='WHR',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
