# Generated by Django 5.0.4 on 2024-05-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_bodyversion_bmi_bodyversion_bmr_bodyversion_whr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyversion',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='وزن'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.IntegerField(default=1),
        ),
    ]
