# Generated by Django 5.0.4 on 2024-05-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_bodyversion_weight_alter_userprofile_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyversion',
            name='BMR',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
