# Generated by Django 5.0.4 on 2024-05-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_bodyversion_bmr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodyversion',
            name='arm_circumference',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='دور بازو'),
        ),
        migrations.AlterField(
            model_name='bodyversion',
            name='chest_circumference',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='دور سینه'),
        ),
        migrations.AlterField(
            model_name='bodyversion',
            name='forehand_circumference',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='دور ساعد'),
        ),
        migrations.AlterField(
            model_name='bodyversion',
            name='hip_circumference',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='دور باسن'),
        ),
        migrations.AlterField(
            model_name='bodyversion',
            name='leg_circumference',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='دور ساق'),
        ),
        migrations.AlterField(
            model_name='bodyversion',
            name='stomach_circumference',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='دور شکم'),
        ),
        migrations.AlterField(
            model_name='bodyversion',
            name='thigh_circumference',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='دور ران'),
        ),
        migrations.AlterField(
            model_name='bodyversion',
            name='waist_circumference',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='دور کمر'),
        ),
    ]
