# Generated by Django 5.0.4 on 2024-06-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_bodyversion_arm_circumference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.IntegerField(default=100),
        ),
    ]
