# Generated by Django 4.1.4 on 2024-04-03 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wrong_phone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09999999999'.\nUp to 11 digits allowed.", regex='^09\\d{9}')]),
        ),
    ]
