# Generated by Django 5.0.4 on 2024-04-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmuscle',
            name='image',
            field=models.ImageField(default='main_muscle/default.png', upload_to='main_muscle'),
        ),
    ]
