# Generated by Django 5.0.4 on 2024-04-24 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_alter_mainmuscle_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='muscle/default.png', upload_to='muscle')),
                ('main_muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.mainmuscle')),
            ],
        ),
    ]
