# Generated by Django 5.0.4 on 2024-04-24 08:17

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_muscle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('image', models.ImageField(default='equipment/default.png', upload_to='equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('english_name', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True)),
                ('place', models.CharField(choices=[('تمرین در منزل', 'تمرین در منزل'), ('تمرین در باشگاه', 'تمرین در باشگاه')], default='تمرین در باشگاه', max_length=128)),
                ('motion_status', models.CharField(choices=[('خوابیده', 'خوابیده'), ('ایستاده', 'ایستاده'), ('نشسته', 'نشسته'), ('ترکیبی', 'ترکیبی')], default='ترکیبی', max_length=128)),
                ('type', models.CharField(choices=[('هوازی', 'هوازی'), ('کششی', 'کششی'), ('کار با وزنه', 'کار با وزنه'), ('وزن بدن', 'وزن بدن')], default='کار با وزنه', max_length=128)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('all', 'all')], default='all', max_length=128)),
                ('image', models.ImageField(default='workout/default.png', upload_to='workout')),
                ('video', models.ImageField(blank=True, null=True, upload_to='workout_video')),
                ('equipment', models.ManyToManyField(to='workout.equipment')),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.muscle')),
            ],
        ),
    ]
