# Generated by Django 5.0.4 on 2024-04-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_equipment_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='hardness',
            field=models.CharField(choices=[('آسان', 'آسان'), ('متوسط', 'متوسط'), ('سخت', 'سخت')], default='all', max_length=128),
        ),
    ]
