# Generated by Django 5.0.4 on 2024-04-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('amount', models.CharField(choices=[('one', 'one'), ('100g', '100g')], default='normal', max_length=20)),
                ('protein', models.IntegerField(default=0)),
                ('carbo', models.IntegerField(default=0)),
                ('sugar', models.IntegerField(default=0)),
                ('fat', models.IntegerField(default=0)),
                ('fiber', models.IntegerField(default=0)),
                ('calorie', models.IntegerField(default=0)),
            ],
        ),
    ]
