# Generated by Django 5.0.4 on 2024-05-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_nutrition_english_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='calorie',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
