# Generated by Django 5.0.4 on 2024-05-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_alter_nutrition_calorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='carbo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='fat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='fiber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='protein',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='nutrition',
            name='sugar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
