# Generated by Django 5.0.4 on 2024-05-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_alter_nutrition_carbo_alter_nutrition_fat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
