# Generated by Django 5.0.4 on 2024-06-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_nutrition_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='amount',
            field=models.CharField(choices=[('one', 'one'), ('100g', '100g')], default='100g', max_length=20),
        ),
    ]
