# Generated by Django 5.0.4 on 2024-04-26 10:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('image', models.ImageField(default='supplement/default.png', upload_to='supplement')),
                ('description', ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True)),
            ],
        ),
    ]
